name: Setup REDAXO

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout des Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # 2. PHP Umgebung einrichten
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: zip, curl, gd

      # 3. Node.js installieren
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 4. Yarn installieren
      - name: Install Yarn
        run: |
          sudo apt-get update
          sudo apt-get install -y yarn

      # 5. Neuste REDAXO Version ermitteln
      - name: Get latest REDAXO release
        id: get_redaxo_release
        run: |
          RELEASE_URL=$(curl -s "https://api.github.com/repos/redaxo/redaxo/releases/latest" | jq -r ".tag_name")
          echo "::set-output name=redaxo_version::$RELEASE_URL"
          SHA=$(curl -Ls "https://github.com/redaxo/redaxo/releases/download/$RELEASE_URL/redaxo_$RELEASE_URL.zip" | shasum -a 1 | awk '{print $1}')
          echo "::set-output name=redaxo_sha::$SHA"

      # 6. Temporäre Verzeichnisse erstellen
      - name: Create temporary directories
        run: |
          mkdir -p tmp/redaxo

      # 7. REDAXO herunterladen
      - name: Download REDAXO
        run: |
          VERSION="${{ steps.get_redaxo_release.outputs.redaxo_version }}"
          SHA="${{ steps.get_redaxo_release.outputs.redaxo_sha }}"
          FILE="tmp/redaxo/redaxo_${VERSION}.zip"
          curl -Ls "https://github.com/redaxo/redaxo/releases/download/${VERSION}/redaxo_${VERSION}.zip" -o "${FILE}"
          echo "File SHA: $(sha1sum ${FILE})"
          if [[ "$(sha1sum ${FILE} | awk '{print $1}')" != "${SHA}" ]]; then
            echo "ERROR: SHA-Hash is incorrect."
            exit 1
          fi

      # 8. REDAXO entpacken
      - name: Unzip REDAXO
        run: |
          VERSION="${{ steps.get_redaxo_release.outputs.redaxo_version }}"
          FILE="tmp/redaxo/redaxo_${VERSION}.zip"
          unzip "${FILE}" -d public

      # 9. Yakamara Ordnerstruktur erstellen
      - name: Create Yakamara file structure
        run: |
          mkdir -p var
          mkdir -p src
          mv public/redaxo/bin/ bin
          mv public/redaxo/cache var/cache
          mv public/redaxo/data var/data
          mv public/redaxo/src/addons src/addons
          mv public/redaxo/src/core src/core
          mv public/LICENSE.md LICENSE.md
          rm public/README.md
          rm public/README.de.md

      # 10. Setup Dateien kopieren
      - name: Copy setup files
        run: |
          cp .github/files/addon.project.boot.php src/addons/project/boot.php
          cp .github/files/console bin/console
          cp .github/files/index.backend.php public/redaxo/index.php
          cp .github/files/index.frontend.php public/index.php
          cp .github/files/AppPathProvider.php src/AppPathProvider.php

      # 11. Addons herunterladen und installieren
      - name: Download and Install Addons
        run: |
          while IFS= read -r addon_url; do
            echo "installing addon: $addon_url"
             
            ADDON_NAME=$(echo "$addon_url" | sed -E 's/.*\///g')
             
            ADDON_REAL_NAME=$(echo "$addon_url" | sed -E 's/.*\///g')

            RELEASE_URL="$addon_url/releases/latest"
            echo  "RELEASE_URL: $RELEASE_URL"
            ZIP_URL=$(curl -s -H 'User-Agent: PHP' "$RELEASE_URL" | jq -r '.zipball_url')
            echo  "ZIP_URL: $ZIP_URL"
             
            curl -Ls "$ZIP_URL" -o "tmp/$ADDON_REAL_NAME.zip"
            unzip "tmp/$ADDON_REAL_NAME.zip" -d tmp

            ADDON_DIR=$(find tmp -maxdepth 1 -type d -name "*-${ADDON_REAL_NAME}-*")
            if [[ -n "$ADDON_DIR" ]]; then
                echo "Found addon dir: $ADDON_DIR"
               mv "$ADDON_DIR" "src/addons/$ADDON_NAME"
            else
                echo "Addon directory not found for $ADDON_REAL_NAME"
            fi
             rm "tmp/$ADDON_REAL_NAME.zip"
          done < addons.txt
        shell: bash

      # 12. Temporäre Verzeichnisse entfernen
      - name: Remove temporary directories
        run: |
          rm -rf tmp/redaxo
          find tmp -maxdepth 1 -type d -exec rm -rf {} +

      # 13. Pull Request erstellen
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: redaxo-setup
          title: "Setup REDAXO structure"
          body: "Automatischer Setup der REDAXO Struktur"
          base: ${{ github.head_ref || github.ref_name }}
          commit-message: "Setup REDAXO structure"
